### ISSUE TITLE
Server ping

### ISSUE THREAD

**Issue by NegativeIQ** [oscar-broman/node-samp-server#3]
How about adding server ping info? Since we are already sending request i guess we could keep track about time taken for response...

**Comment by oscar-broman** [comment]
Which ping do you mean? Player ping or something else?

**Comment by NegativeIQ** [comment]
Server ping to client (our js query client), in other words time taken from sending request until response from server.

**Comment by oscar-broman** [comment]
What server? There is no network server in this (besides SA-MP).

**Comment by NegativeIQ** [comment]
Oh sorry, my bad, i was meaning to send these to node-samp-query by JJJ4n, and somehow managed to post here...Sorry again xD
